import type { Metadata } from "next";
import Navbar from "./_components/Navbar";
import "./globals.css";

import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <title>Lacrei Saúde</title>
      <link rel="icon" href="../public/LS logo.png" />
      <body>
        {children}
      </body>
    </html>
  );
}
