import type { Metadata } from "next";
import Navbar from "./_components/Navbar";
import "./globals.css";
import Logo from "./_images/LS-logo.png"
import Link from "next/link";

export const metadata: Metadata = {
  title: "Lacrei Saúde",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <title>Lacrei Saúde</title>
      <link rel="icon" href={Logo.src} />
      <body>
        {children}
      </body>
    </html>
  );
}
